#!/bin/sh

PROGNAME="${0##*/}"
PROGDIR="${0%/*}"

set -e

cd "${PROGDIR}"
docker build --tag yasvpn:latest .
exec docker run -it --rm -p 1080:1080 -p 3389:3389 -e REMOTEDESKTOP_HOST=${REMOTEDESKTOP_HOST:-host.example.net} -e GLOBALPROTECT_PORTAL=${GLOBALPROTECT_PORTAL:-some.vpn.host.example.com} --name yasvpn yasvpn:latest "$@"
